Login_Project/Login_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from login import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name='index'),
    path('app/',include('login.urls')),
    path('logout/',views.user_logout, name='logout')
]

Login_Project/login/urls.py
from django.urls import path, include
from login import views

app_name = 'login'

urlpatterns = [
    path('register/', views.register, name = 'register'),
    path('login/', views.user_login, name='user_login'),
]

Login_Project/login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class userProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE,)

    LinkedInSite = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics'  , blank=True)

    def __str__(self):
        return self.user.username

Login_Project/login/forms.py
from django import forms
from django.contrib.auth.models import User
from login.models import userProfile

class userForm(forms.ModelForm):

    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class userProfileForm(forms.ModelForm):


    class Meta():
        model = userProfile
        fields = ('LinkedInSite', 'profile_pic')

Login_Project/login/views.py
from django.shortcuts import render
from login.forms import userForm,userProfileForm

from django.urls import reverse
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout

# Create your views here.
def index(request):
    return render(request, 'login/index.html')

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = userForm(data=request.POST)
        profile_form = userProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save( )

            registered = True
        
        else:
            print(user_form.errors,profile_form.errors)

    else:

        user_form = userForm()
        profile_form = userProfileForm()
    
    return render(request,'login/registration.html', {'registered': registered,
                                                       'userForm': user_form,
                                                       'userProfileForm': profile_form})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('Password')

        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to login")
            print("Username: {} Password: {}".format(username,password))
            return HttpResponse('Invalid Response')
    else:
        return render(request,'login/login_page.html',{})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def test_login(request):
    return HttpResponse('Not logged in')

Login_Project/templates/login/base.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
            integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'index' %}">Home</a>
            <div class="navbar-nav ">
                <ul class="navbar-nav mr-auto">
                    <li class="navbar-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li class="navbar-item"><a class="nav-link" href="{% url 'login:register' %}">Register</a></li>
                
                    {% if user.is_authenticated %}
                        <li class="navbar-item"><a class="nav-link" href="{% url 'logout' %}">logout</a></li>
                    {% else %}
                        <li class="navbar-item"><a class="nav-link" href="{% url 'login:user_login' %}">login</a></li>
                    {% endif %}
                    </ul>
            </div>
        </nav>

        <div class="container">
            {% block body_block%}
            {% endblock%}
        </div>
        
    </body>
</html>

Login_Project/templates/login/index.html
{% extends "login/base.html"%}
{% block body_block%}

<div class="jumbotron">
    <h1> Registration and Login</h1>
</div>

{% endblock %}

Login_Project/templates/login/login_page.html
{% extends "login/base.html" %}
{% block body_block%}

<div class="jumbotron">
    <h1> Login here </h1><br>
    <form action="{% url 'login:user_login' %}" method="POST">
    {% csrf_token %}
    <label for="Username"> Username </label>
    <input type="text" name="username" placeholder="Enter here">

    <label for="Password"> Password </label>
    <input type="password" name="Password">

    <input type="submit" value="Login">
    
    </form>
</div>

{% endblock %}

Login_Project/templates/login/registration.html
{% extends "login/base.html" %}


{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h1>Registered Successfully</h1>
    {% else %}
        <h1> Register Here!!</h1><br>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{userForm.as_p}}
            {{userProfileForm.as_p}}
            <input type="submit" value="Register">
        </form>
    {% endif%}
</div>

{% endblock %}